services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:${OAUTH2_PROXY_VERSION:-latest}
    container_name: oauth2-proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 4180:4180
    command: --config /run/secrets/oauth2-proxy.cfg
    secrets:
      - oauth2-proxy.cfg
      - .htpasswd

secrets:
  oauth2-proxy.cfg:
    file: ./oauth2/secrets/oauth2-proxy.cfg
  .htpasswd:
    file: ./oauth2/secrets/.htpasswd
