#!/bin/bash

# EC2 UserData script for Norsk Studio installation
# Generated by Terraform - do not edit directly

set -euxo pipefail

# Capture output
exec >/var/log/ec2-userdata.log 2>&1

# Install git
apt-get update
apt-get install -y git

# Install awscli
snap install aws-cli --classic


# Get IMDSv2 token
TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")

# Get region for SSM
REGION=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" \
  http://169.254.169.254/latest/meta-data/placement/region)

# Fetch secrets from SSM Parameter Store
echo "Fetching secrets from SSM..."
NORSK_LICENSE=$(aws ssm get-parameter \
  --name /norsk/license \
  --with-decryption \
  --query 'Parameter.Value' \
  --output text \
  --region "$REGION")

STUDIO_PASSWORD=$(aws ssm get-parameter \
  --name /norsk/password \
  --with-decryption \
  --query 'Parameter.Value' \
  --output text \
  --region "$REGION")

# Fetch optional config from instance tags (allow failures)
DOMAIN_NAME=$(curl -sf -H "X-aws-ec2-metadata-token: $TOKEN" \
  http://169.254.169.254/latest/meta-data/tags/instance/DomainName || echo "")

CERTBOT_EMAIL=$(curl -sf -H "X-aws-ec2-metadata-token: $TOKEN" \
  http://169.254.169.254/latest/meta-data/tags/instance/CertbotEmail || echo "")

HARDWARE_OVERRIDE="${hardware_override}"

# Clone repo
mkdir -p /var/norsk-studio
cd /var/norsk-studio
git clone -b ${repo_branch} https://github.com/norskvideo/norsk-studio-docker.git

cd /var/norsk-studio/norsk-studio-docker

# Run bootstrap
./scripts/bootstrap.sh \
  --platform=aws \
  --hardware="$HARDWARE_OVERRIDE" \
  --license="$NORSK_LICENSE" \
  --password="$STUDIO_PASSWORD" \
  --domain="$DOMAIN_NAME" \
  --certbot-email="$CERTBOT_EMAIL"

# Reboot if GPU hardware detected (check installed config)
if grep -q 'DEPLOY_HARDWARE="nvidia"' deployed/*/norsk-config.sh 2>/dev/null; then
  echo "NVIDIA hardware detected, rebooting..."
  reboot
fi
