#!/usr/bin/env bash
set -eo pipefail
# Completes setup after cloning repo to targetDir.
# Pulls containers and downloads sample media.

oops() {
    echo "$0:" "$@" >&2
    exit 1
}

usage() {
    echo "Usage: $(basename "$0") targetDir" >&2
    exit 1
}

# The top level installer has already checked that one of these is available...
if command -v curl > /dev/null 2>&1; then
    fetch() { curl  --silent --fail -L "$1" -o "$2"; }
else
    fetch() { wget --quiet "$1" -O "$2"; }
fi

pull() {
    DOCKER_CLI_HINTS=false docker pull $1
}

main() {
    local -r targetDirname=$1

    # Load container versions
    source "$targetDirname/versions"

    # Do a dry run of the compose command to make sure that the installed version is compatible with our YAML
    tmpOutput=$(mktemp)
    tmpMerge=$(mktemp)
    "$targetDirname/up.sh" --merge "$tmpMerge" > "$tmpOutput" 2>&1 || true
    if [[ -f "$tmpOutput" ]]; then
        rm "$tmpOutput"
        rm "$tmpMerge"
    else
        echo "A trail run failed, with output"
        cat "$tmpOutput"
        rm "$tmpOutput"
        rm "$tmpMerge"
        oops "Please check permissions and Docker Compose version"
    fi

    local containers=("$NORSK_MEDIA_IMAGE" "$NORSK_STUDIO_IMAGE")

    echo "Downloading containers:"
    for container in "${containers[@]}" ; do
        echo
        echo "Downloading $container"
        pull "$container"
        echo

    done

    # Pull down the sample media files
    echo "Downloading media samples"
    sourcesDir="$targetDirname/data/media"
    mkdir -p "$sourcesDir"
    for source in action.mp4 wildlife.ts ; do
        fetch "https://s3.eu-west-1.amazonaws.com/norsk.video/media-examples/data/$source" "$sourcesDir/$source"
    done

    echo
    echo "Installation complete."
    echo
    echo "To start Norsk Studio, change to the $targetDirname directory"
    echo "and run the 'up.sh' script. Typing the following commands"
    echo "should get you started..."
    echo
    echo "cd $targetDirname"
    echo "./up.sh"
    echo
    echo "If you want to send in a sample SRT source to the example workflows,"
    echo "then you can use e.g."
    echo
    echo "./sample-srt-source.sh camera1 start"
    echo "./sample-srt-source.sh camera2 start"
    echo
    echo "Running './up.sh --help' will show you the command line options."
    echo
    echo "To stop Norsk Studio (and any sample sources), just run"
    echo
    echo "./down.sh"
    echo
    echo
    echo "Thank you for installing.  Enjoy using Norsk Studio!"
    echo "Do let us know how you get on."
    echo
}

if [[ "$#" -ne 1 ]]; then
    usage
else
    if [[ ! -d "$1" ]]; then
        echo "Target directory not found: $1" >&2
        usage
    fi
fi

main "$@"